lookalone_1 = ""

def notdone ():
    print ("")
    print ("... in progress... loading...sorry, try a different option.")

def stayhome4 ():
    print ("")
    print ("Ten days pass and the adventurers return with thirty extra warriors.")
    print ("One comes over to you saying, 'I hear you are a strong fire mage. Is that true?'")
    print ("You reply with, 'Yes. I do have fire magic. But, I do not wish to accompany you to the Demon King's castle. I only want to stay down here, in Falcon Feather.'")
    print ("The adventurer seems disappointed, but doesn't push, simply saying, 'If that is what you want...' and walks away.")
    print ("The day after their arrival, the adventurers depart to the Demon Lord's domain.")
    print ("")
    print ("The whole of Falcon Feather is tense, yet goes on with their everyday life.")
    print ("")
    print ("The day crawls by. Then comes the sleepless night.")
    print ("")
    print ("The next day, the town awakes early.")
    print ("To the sound of marching feet.")
    print ("And then an army of orcs is upon you.")
    print ("Within moments, the small, pretty town of Falcon Feather is")
    print ("destroyed.")
    print ("")
    print ("All you see is blackness.")
    print ("All you feel is numbness.")
    print ("All you know is death.")
    print ("")
    print ("")
    print ("GAME OVER")
    print ("")
    print (f"Thanks for playing {name}!")
    print ("That was a sad way to die. Not even fighting! You should try again, but be smarter this time!")

def joinadbenturers2 ():
    print ("")
    print ("Ten days pass quickly. The adventurers are back with thirty extra warriors. You note they have no mages, so your contribution will be very helpful. ")
    print ("You welcome them back to Falcon Feather and tell them about your decision to join them.")
    print ("They accept you with gratitude, saying they have need of your magic abilities.")
    print ("")
    print ("The next day, you depart. You head up the mountain, clad in armor.")
    print ("")
    if lookalone_1 == "B" or lookalone_1 == "b" or lookalone_1 == "B." or lookalone_1 == "b." :
        print ("You make it to the castle. You shiver, remembering you near-death experience just a week and a half earlier.")
        print ("The archers aim their bows at the Demon King, who was in conversation with the same huge orc.")
        print ("Even though he is distracted, the Demon King shoots a burst of fire in the arrows' direction, disintegrating them all.")
        print ("The Demon King sets his evil, black eyes onto you.")
        print (f"'Cast something at him {name}!' The voice of an adventurer jolts you out of your trance of fear.")
        print ("You nod at the adventurer and begin to cast a spell.")
        print ("You start your incantation, your voice shaking, 'Fire, come forth I som-")
        print ("Before you can finish, the Demon Lord angles his hand in your direction.")
        print ("Without saying a word, a burst of fire shoots from his hand.")
        print ("Directly... at you.")
        print ("Before you can even think of doing anything, it's all over.")
        print ("")
        print ("All you see is blackness.")
        print ("All you feel is numbness.")
        print ("All you know is death.")
        print ("")
        print ("")
        print ("GAME OVER")
        print ("")
        print (f"Thanks for playing {name}!")
        print ("Well, at least you died fighting. Could be worse. But, it could be better. Maybe. Want to play again and see?")
        
    else:
        print ("You make it to the castle.")
        print ("Inside, there is only one huge room. The throne room.")
        print ("You can barely make it out, but you think you see a huge man, twenty, or maybe thirty, feet tall - sitting in a big throne.")
        print ("He is wearing a jet black robe and an obsidian crown.")
        print ("His eyes... oh his eyes... are scary. You shiver looking at them. No whites, just black on black.")
        print ("")
        print ("He is talking to an orc. Or, at least, you think it's an orc. It is twice as big as the orcs you usually see near your village.")
        print ("Anyway, they are talking, but not in English. They are saying something in an ancient language. You can tell that much just by how it sounds:")
        print ("")
        print ("'Hondrach gombink hooblylac demononist-' the Demon Lord says.")
        print ("")
        print ("The archers aim their bows at the Demon King.")
        print ("Even though he is distracted, the Demon King shoots a burst of fire in the arrows' direction, disintegrating them all.")
        print ("The Demon King set his evil, black eyes on you.")
        print (f"'Cast something at him {name}!' The voice of an adventurer jolts you out of your trance of fear.")
        print ("You nod at the adventurer and begin to cast a spell.")
        print ("You start your incantation, your voice shaking, 'Fire, come forth I som-")
        print ("The Demon Lord angles his hand in your direction.")
        print ("Without saying a word, a burst of fire comes from his hand.")
        print ("Directly... at you.")
        print ("Before you can even think of doing anything, it's all over.")
        print ("")
        print ("All you see is blackness.")
        print ("All you feel is numbness.")
        print ("All you know is death.")
        print ("")
        print ("")
        print ("GAME OVER")
        print ("")
        print (f"Thanks for playing {name}!")
        print ("Well, at least you died fighting. Could be worse. But, it could be better. Maybe. Want to play again and see?")

def freeze1 ():
    print ("")
    print ("You stand perfectly still.")
    print ("You close your eyes.")
    print ("You hold your breath")
    print ("You are ready. For whatever will happen next.")
    print ("")
    print ("")
    print ("You wait")
    print ("")
    print ("")
    print ("And wait")
    print ("")
    print ("")
    print ("You squint one eye open.")
    print ("")
    print ("")
    print ("You wish you hadn't.")
    print ("An army of orcs are coming your way, armed with spears.")
    print ("So close.")
    print ("The closest orc stabs you and everything is gone.")
    print ("")
    print ("All you see is blackness.")
    print ("All you feel is numbness.")
    print ("All you know is death.")
    print ("")
    print ("")
    print ("GAME OVER")
    print ("")
    print (f"Thanks for playing {name}!")
    print ("Try again. It won't bother me. I have nothing else to do anyway.")

def fight1 ():
    print ("")
    print ("You are ready. Or as ready as someone hoping to best one of the strongest creatures in existence could be.")
    print ("You raise your fists.")
    print ("You cast an incantation, your voice shaking, 'Fire, come forth I som-")
    print ("Before you can finish, the Demon Lord angles his hand in your direction.")
    print ("Without saying a word, a burst of fire shoots from his hand.")
    print ("Directly... at you.")
    print ("Before you can even think of doing anything, it is all over.")
    print ("")
    print ("All you see is blackness.")
    print ("All you feel is numbness.")
    print ("All you know is death.")
    print ("")
    print ("")
    print ("GAME OVER")
    print ("")
    print (f"Thanks for playing {name}!")
    print ("Feel free to try again. Without dying, preferably.")

def flight1 ():
    print ("")
    print ("You jolt backwards, back behind the wall you were previously behind.")
    print ("You wait for a moment then burst into frantic running, desperately hoping to escape with your life.")
    print ("You look back for just a moment and see... nothing.")
    print ("Nothing was following you!")
    print ("Your not sure if that means you're too weak to be cared about, but you are happy for the miracle.")
    print ("")
    print ("Though nothing is following you, you run anyway. All the way down Mt. Eagle.")
    print ("")
    print ("When you reach the village, you find the adventurers are gone, reporting to the capital.")
    print ("They said the Demon King won't do anything as long as their forces are still growing. It's just enough time for the adventurers to fetch help.")
    print ("You are to wait for their return in approximately ten days.")
    print ("In that time, you think up two options to proceed with:")
    print ("")
    print ("A. Join the adventurers to help them fight the Demon Lord. This is your village. You will not let it fall.")
    print ("B. You can leave the fighting to the adventurers. They know what they're doing and won't take any shortcuts.")
    print ("")
    flight_1 = input ("")
    if flight_1 == "A" or flight_1 == "a" or flight_1 == "A." or flight_1 == "a." :
        joinadbenturers2 ()
    elif flight_1 == "B" or flight_1 == "b" or flight_1 == "B." or flight_1 == "b." :
        stayhome4 ()
    else:
        print ("")
        print (f"Hmmm... Looks like you didn't choose one of the options {name}. Just type a or b, not the whole sentence, okay?")
        print ("")
        redoanswer5 = input ("")
        if redoanswer5 == "A" or redoanswer5 == "a" or redoanswer5 == "A." or redoanswer5 == "a." :
            joinadbenturers2 ()
        elif redoanswer5 == "B" or redoanswer5 == "b" or redoanswer5 == "B." or redoanswer5 == "b." :
            stayhome4 ()
        else:
            print ("")
            print ("OK!!! STOP BEING ANNOYING!!! JUST CHOOSE SOMETHING!!! ACTUALLY, SCRATCH THAT! LEAVE ME ALONE AND TRY AGAIN WHEN YOU CAN HANDLE THIS!!!")

def lookalone1 ():
    print ("")
    print ("You quickly leave the group of villagers, heading towards Mt. Eagle. Soon enough, you get to its base.")
    print ("You peer up to the top. You mentally prepare yourself and begin the trek.")
    print ("")
    print ("")
    print ("")
    print ("You finally get to your destination; the Demon Lord's castle! 'How did we never realize this was here?' you ask yourself.")
    print ("You peek around the corner, your heart hammering in your chest.")
    print ("You can barely make it out, but you think you see a huge man, twenty, or maybe thirty, feet tall - sitting in a big throne.")
    print ("He is wearing a jet black robe and an obsidian crown.")
    print ("His eyes... oh his eyes... are scary. You shiver looking at them. No whites, just black on black.")
    print ("")
    print ("He is talking to an orc. Or, at least, you think it's an orc. It is twice as big as the orcs you usually see near your village.")
    print ("Anyway, they are talking, but not in English. They are saying something in an ancient language. You can tell that much just by how it sounds:")
    print ("")
    print ("'Hondrach gombink hooblylac demononist-' the Demon Lord says, then it stops abruptly.")
    print ("It put its nose in the air, sniffing. Then, as sudden and fast as a snake, his head turns.")
    print ("The Demon Lord casts his creepy stare on you.")
    print ("The Demon Lord-")
    print ("The evilest creature in existence-")
    print ("Is looking at")
    print ("you.")
    print ("Your blood freezes.")
    print ("You have but three options:")
    print ("")
    print ("A. Freeze. You can hope the Demon Lord doesn't see you, or at least doesn't bother killing you.")
    print ("B. Flight. Run. Escape so the Demon Lord doesn't catch you. That is, hide, and then run.")
    print ("C. Fight. Your fire magic is decent, it's worth a shot.")
    print ("")
    global lookalone_1
    lookalone_1 = input ("")
    if lookalone_1 == "A" or lookalone_1 == "a" or lookalone_1 == "A." or lookalone_1 == "a." :
        freeze1 ()
    elif lookalone_1 == "B" or lookalone_1 == "b" or lookalone_1 == "B." or lookalone_1 == "b." :
        flight1 ()
    elif lookalone_1 == "C" or lookalone_1 == "c" or lookalone_1 == "C." or lookalone_1 == "c." :
        fight1 ()
    else:
        print ("")
        print (f"Hmmm... Looks like you didn't choose one of the options {name}. Just type a, b, or c, not the whole sentence, okay?")
        print ("")
        redoanswer4 = input ("")
        if redoanswer4 == "A" or redoanswer4 == "a" or redoanswer4 == "A." or redoanswer4 == "a." :
            freeze1 ()
        elif redoanswer4 == "B" or redoanswer4 == "b" or redoanswer4 == "B." or redoanswer4 == "b." :
            flight1 ()
        elif redoanswer4 == "C" or redoanswer4 == "c" or redoanswer4 == "C." or redoanswer4 == "c." :
            fight1 ()
        else:
            print ("")
            print ("OK!!! STOP BEING ANNOYING!!! JUST CHOOSE SOMETHING!!! ACTUALLY, SCRATCH THAT! LEAVE ME ALONE AND TRY AGAIN WHEN YOU CAN HANDLE THIS!!!")

def stayhome3 ():
    print ("")
    print ("You leave the group and head home.")
    print ("The leader of the adventurers comes over to you asking, 'Would you join us? We hear you have an exceptional magic ability.")
    print ("'Sorry, no. I need to protect my family above all,' you tell them.")
    print ("The adventurer looks disappointed, but leaves at that.")
    print ("")
    print ("Later, you hear that the adventurers left, reporting to the capital.")
    print ("They said the Demon King won't do anything as long as there forces are still growing. Just enough time for the adventurers to fetch help.")
    print ("You are to wait for their return in approximately ten days.")
    print ("In that time, you think up two options to proceed with:")
    print ("")
    print ("A. Join the adventurers to help them fight the Demon Lord. Mages are rare. Your help will make a difference. The risk is low, with the reinforcements coming.")
    print ("B. You can leave the fighting to the adventurers. They know what they're doing and won't take any shortcuts.")
    print ("")
    stayhome_3 = input ("")
    if stayhome_3 == "A" or stayhome_3 == "a" or stayhome_3 == "A." or stayhome_3 == "a." :
        joinadbenturers2 ()
    elif stayhome_3 == "B" or stayhome_3 == "b" or stayhome_3 == "B." or stayhome_3 == "b." :
        stayhome4 ()
    else:
        print ("")
        print (f"Hmmm... Looks like you didn't choose one of the options {name}. Just type a or b, not the whole sentence, okay?")
        print ("")
        redoanswer6 = input ("")
        if redoanswer6 == "A" or redoanswer6 == "a" or redoanswer6 == "A." or redoanswer6 == "a." :
            joinadbenturers2 ()
        elif redoanswer6 == "B" or redoanswer6 == "b" or redoanswer6 == "B." or redoanswer6 == "b." :
            stayhome4 ()
        else:
            print ("")
            print ("OK!!! STOP BEING ANNOYING!!! JUST CHOOSE SOMETHING!!! ACTUALLY, SCRATCH THAT! LEAVE ME ALONE AND TRY AGAIN WHEN YOU CAN HANDLE THIS!!!")

def joinadbenturers1 ():
    print ("")
    print ("You run to the front of the crowd, telling the adventurers 'I want to help you! I am strong! Please let me help!'")
    print ("The crowd of bystanders gasp. The adventurers smile through their pain, 'Of course you can come! We would be honored!'")
    print ("The adventurer who spoke continues, 'Come with us for a quick lesson from the academy. we are heading for the capital to gather reinforcements.'")
    print ("At your crestfallen expression, they explain, 'We will be resting there for two days. Learn in those moments, I hear even the smallest bits of professional help gives great improvement for self-taught mages!'")
    print ("You nod, ready to help your village.")
    print ("")
    print ("You make it to the capital and then the academy, taking quick lessons. You are surprised at how much you improved in just two days.")
    print ("You start heading back to Falcon Feather with reinforcements of ten archers, one healer, and thirty new adventurers, replacing the eleven injured ones.")
    print ("")
    print ("You make it back to your town and get ready.")
    print ("")
    print ("The next day, you head out.")
    print ("")
    print ("You finally get to your destination; the Demon Lord's castle! 'How did we never realize this was here?' you ask yourself.")
    print ("You peek around the corner, your heart hammering in your chest. The rest of your group is behind you.")
    print ("You can barely make it out, but you think you see a huge man, twenty, or maybe thirty feet tall - sitting in a big throne.")
    print ("He is wearing a jet black robe and an obsidian crown.")
    print ("His eyes... oh his eyes... they're scary. You shiver looking at them. No whites, just black on black.")
    print ("")
    print ("He is talking to an orc. Or, at least, you think it's an orc. It is twice as big as the orcs you usually see near your village.")
    print ("Anyway, they were talking, but not in English. They were saying something in an ancient language. You can tell that much just by how it sounds:")
    print ("")
    print ("'Hondrach gombink hooblylac demononist...' the Demon Lord says.")
    print ("")
    print ("The archers aim their bows at the Demon King, who is still in conversation with the huge orc.")
    print ("Even though he is distracted, the Demon King shoots a burst of fire in the arrows' direction, disintegrating them all.")
    print ("The Demon King sets his evil, black eyes on you.")
    print (f"'Cast something at him {name}!' The voice of an adventurer jolts you out of your trance of fear.")
    print ("You nod at the adventurer and began to cast a spell.")
    print ("Meanwhile, a army of orcs is coming towards your group")
    print ("You start your incantation, your voice shaking, 'Fire, come forth, I summon you. Disintegrate my foe!'")
    print ("A huge burst of flame emerges from your open palm.")
    print ("The fire does indeed disintegrate your foes.")
    print ("All the orcs in range, about half of their force, is destroyed.")
    print (f"'Amazing job {name}!' an adventurer calls, 'Wait a little for them to get in range and do that again!'")
    print ("You nod, though you can only cast that spell two more times.")
    print ("")
    print ("As the adventurer suggested, you wait, then cast it again.")
    print ("All but a few stragglers are destroyed. Those extras are quickly dispatched by the adventurers.")
    print ("Finally, all that is left is the Demon Lord himself.")
    print ("")
    print (f"'Surround him!' an adventurer calls. 'Protect {name} while they cast their spell!'")
    print ("The other adventurers do as the leader says, readying their arrows and swords.")
    print ("'Ready?' They ask you. ")
    print ("You nod and cast your spell once more.")
    print ("You don't have much magic power left after casting the spell, causing you to pass out.")
    print ("")
    print ("All you see is blackness.")
    print ("All you can feel is numbness.")
    print ("All you know is... You don't know.")
    print ("")
    print ("You open your eyes to a party.")
    print (f"'{name} finally woke up!' someone calls.")
    print ("You blink your bleary eyes.")
    print ("")
    print ("Someone explains to you that your magic blast injured the Demon Lord enough to let the adventurers finish them!")
    print ("You are the hero of the town!")
    print ("You won!")
    print ("")
    print ("GAME OVER")
    print ("")
    print (f"Thanks for playing {name}!")
    print ("You became a hero and all that is great. But don't you want to experience it, not just be told once you wake up? If you do, play again!")

def academy3 ():
    print ("")
    print ("You push through the crowd, looking for your parents.")
    print ("Finally, you see their horrified faces. You squirm through the tightly packed space, over to them.")
    print ("'I want to go to the capital,' you yell to them.")
    print ("Your parents exchange relieved glances, smiling.")
    print ("Your mother tells you, 'Please, though your application is late, I'm sure they would accept an amazing fire mage like you.'")
    print ("'Yes, and the adventures will being going to the capital for reinforcements too. You could join them as they travel,' your father smiles.")
    print ("'Okay,' you respond.")
    print ("")
    print ("Your father waves over an adventurer and tells them his request.")
    print ("They agree, telling you they will leave tomorrow.")
    print ("")
    print ("You say your goodbyes and head to the capital.")
    print ("")
    print ("You finally get to the capital and enter your classes a month late.")
    print ("School life suites you well. You make lots of friends and learn to use strong magic.")
    print ("A month into school, you overhear some teachers talking about the Demon Lord.")
    print ("")
    print ("'Did you hear,' one says to another. 'A whole town. Destroyed!'")
    print ("Something deep in your stomach shifts.")
    print ("'Poor Falcon Feather.'")
    print ("")
    print ("No")
    print ("")
    print ("No")
    print ("")
    print ("Not Falcon Feather.")
    print ("")
    print ("What had happened to your family? Your friends? Your community? Your old life?")
    print ("Gone?\n")
    print ("Had anyone escaped?")
    print ("\nYou are hyperventilating, breaths coming in short gasps.\n")
    print ("'Don't we have a student from there? Do they know?' One of the teachers asks.\n")
    print ("You are lightheaded.")
    print ("")
    print ("Suddenly, the ground seems too close.")
    print ("All is black.")
    print ("")
    print ("You wake up in a bed.")
    print ("Your friends are there, relieved to see you safe after a day long rest.")
    print ("")
    print ("You later learn, in fact, there were no survivors from Falcon Feather.")
    print ("More towns had been destroyed and a squad of mages and adventurers had finally gone to confront the Demon King.")
    print ("")
    print ("A week later you learn they won.")
    print ("")
    print ("GAME OVER")
    print ("")
    print (f"Thanks for playing {name}!")
    print ("You won! ... Maybe? Well, you survived with some new friends, but the kingdom was ravaged and your whole town was killed, including all your childhood friends and family.")
    print ("Woo hoo. Anyway, that seemed like a sad way to win. I am hopeful that there is a slightly better option than that. Try to find it. I would rather that not be in my memory system.")

def stayhome2 ():
    print ("")
    print ("Dinner comes ever so quickly and you tell you parents your decision to stay home. They don't look too pleased, but they know they can't change you mind.")
    print ("")
    print ("")
    print ("")
    print ("Time passes. Days turn to weeks, turn to months. You are starting to think that the Demon King stuff is nonsense. You get comfortable in your small village. Too comfortable.")
    print ("")
    print ("Then, something that has NEVER happened before happens. Fifteen adventurers from the capital come to your village! They, for some reason, think there is evidence of the Demon King's revival in your town!")
    print ("You assure them there is no reason to investigate. You would have noticed something unusual. Right?")
    print ("Yet, they look around anyway. They spend days looking around Mt. Eagle, which is just east of Falcon Feather.")
    print (f"You are starting to think that maybe they moved on, when when a villager comes running over, saying 'They're back! The adventurers! Come quick {name}!'")
    print ("You come running over to see a sight you were not expecting. Instead of the proud group of strong adventurers, there are now just eleven stragglers. They are all badly hurt and barely staggering by.")
    print ("They tell you that they found the Demon Lord and tried fighting. That is what happened.")
    print ("This changes things. What will you do? So many options are swirling through your head.")
    print ("")
    print ("A. You could always change your mind and prepare for the fight by going to the academy. As your parents said, it is safe and a place where you could learn to be as powerful as possible.")
    print ("B. You could join the adventurers and see for yourself. You have fire magic. You have been practicing at home, after all. ")
    print ("C. You could stay home and let the professionals deal with it. You're curious, but they know what they are doing, right?")
    print ("D. You could look alone, see for yourself, and run back up the mountain. These adventurers don't seem all that trustworthy.")
    print ("")
    stayhome_2 = input ("")
    if stayhome_2 == "A" or stayhome_2 == "a" or stayhome_2 == "A." or stayhome_2 == "a." :
        academy3 ()
    elif stayhome_2 == "B" or stayhome_2 == "b" or stayhome_2 == "B." or stayhome_2 == "b." :
        joinadbenturers1 ()
    elif stayhome_2 == "C" or stayhome_2 == "c" or stayhome_2 == "C." or stayhome_2 == "c." :
        stayhome3 ()
    elif stayhome_2 == "D" or stayhome_2 == "d" or stayhome_2 == "D." or stayhome_2 == "d." :
        lookalone1 ()
    else:
        print ("")
        print (f"Hmmm... Looks like you didn't choose one of the options {name}. Just type a or b, not the whole sentence, okay?")
        print ("")
        redoanswer3 = input ("")
        if redoanswer3 == "A" or redoanswer3 == "a" or redoanswer3 == "A." or redoanswer3 == "a." :
            academy1 ()
        elif redoanswer3 == "B" or redoanswer3 == "b" or redoanswer3 == "B." or redoanswer3 == "b." :
            joinadbenturers1 ()
        elif redoanswer3 == "C" or redoanswer3 == "c" or redoanswer3 == "C." or redoanswer3 == "c." :
            stayhome3 ()
        elif redoanswer3 == "D" or redoanswer3 == "d" or redoanswer3 == "D." or redoanswer3 == "d." :
            lookalone1
        else:
            print ("")
            print ("OK!!! STOP BEING ANNOYING!!! JUST CHOOSE SOMETHING!!! ACTUALLY, SCRATCH THAT! LEAVE ME ALONE AND TRY AGAIN WHEN YOU CAN HANDLE THIS!!!")

def academy2 ():
    print ("")
    print ("You come to dinner, confirming with your parents about your decision to go to the capital.")
    print ("Your parents exchange an elated glance.")
    print ("'We are so happy you decided to go to the capital,' your mother tells you.")
    print ("Your father nods. 'We couldn't be happier for you.'")
    print ("You smile, knowing you made the right choice.")
    print ("")
    print ("The two days slowly pass. Then, finally, the time comes to travel to the academy where your studies will begin.")
    notdone ()

def academy1 ():

    print ("")
    print (f"Good choice {name}! Clearly, you want to learn about fire magic.")
    print ("")
    print ("You tell your parents that you want to go to the magic academy to study fire magic.")
    print ("They tell you that you can go, but since it is still early, you can't go until next month.")
    print ("You groan, but agree, knowing you wouldn't get a better deal.")
    print ("")
    print ("You are relaxing, leaving for the capital in two days, and enjoying your last few days of summer break, when your father and mother come running over.")
    print ("Your father starts, telling you 'Reports say the Demon King is back! I am so happy you want to go to the capital. I wish I could go with you.'")
    print ("You smile reassuringly back at them, but secretly, this makes going to the capital more of a decision then it ever was before.")
    print ("Your mother nods, clearly relieved, 'Go get ready to leave for the capital. See you at dinner tonight'")
    print ("'Ok, mom.'")
    print ("")
    print ("")
    print ("You head to your room, considering the options:")
    print ("")
    print ("A. You could do as your parents suggested and go to the capital as planed, study magic, and stay safe from the Demon Lord. Yet, you love your parents. If they are in danger, you cant leave them!")
    print ("B. You could stay home, where you feel most comfortable. You wouldn't have to worry about your parents and you could study without an official tutor if you wanted.")
    print ("")
    stayhome_1 = input ("")
    if stayhome_1 == "A" or stayhome_1 == "a" or stayhome_1 == "A." or stayhome_1 == "a." :
        academy2 ()
    elif stayhome_1 == "B" or stayhome_1 == "b" or stayhome_1 == "B." or stayhome_1 == "b." :
        stayhome2 ()
    else:  
        print ("")
        print (f"Hmmm... Looks like you didn't choose one of the options {name}. Just type a, b, or c, not the whole sentence, okay?")
        print ("")
        redoanswer2 = input ("")
        if redoanswer2 == "A" or redoanswer2 == "a" or redoanswer2 == "A." or redoanswer2 == "a." :
            academy2 ()
        elif redoanswer2 == "B" or redoanswer2 == "b" or redoanswer2 == "B." or redoanswer2 == "b." :
            stayhome2 ()
        else:
            print ("")
            print ("OK!!! STOP BEING ANNOYING!!! JUST CHOOSE SOMETHING!!! ACTUALLY, SCRATCH THAT! LEAVE ME ALONE AND TRY AGAIN WHEN YOU CAN HANDLE THIS!!!")
        
def stayhome1 ():
    print ("")
    print (f"Alright {name}. It IS only June. Submissions for school are due in two whole months!")
    print ("")
    print ("You are having a relaxing few weeks when your father and mother come running over, their expressions scared.")
    print ("")
    print (f"Your father starts, telling you 'I know you said you didn't want to go to school {name}, but it's urgent. Reports say the Demon King is back! You need the protection of the capital and the training from the academy to protect yourself! Please {name}!' ")
    print ("'Ummmmmm... let me think on that,' you respond, looking between your parents.")
    print ("Your mother nods, clearly relieved, 'Please tell us your decision at dinner tonight'")
    print ("'Ok, mom.'")
    print ("")
    print ("")
    print ("You head to your room, considering the options:")
    print ("")
    print ("A. You could do as your parents suggested, go to the capital to study magic and stay safe from the Demon Lord. Yet, you love Falcon Feather. It isn't too small nor too big.")
    print ("B. You could stay home, where you feel most comfortable. You wouldn't have to worry about your parents and you could study without an official tutor if you wanted.")
    print ("")
    stayhome_1 = input ("")
    if stayhome_1 == "A" or stayhome_1 == "a" or stayhome_1 == "A." or stayhome_1 == "a." :
        academy2 ()
    elif stayhome_1 == "B" or stayhome_1 == "b" or stayhome_1 == "B." or stayhome_1 == "b." :
        stayhome2 ()
    else:  
        print ("")
        print (f"Hmmm... Looks like you didn't choose one of the options {name}. Just type a, b, or c, not the whole sentence, okay?")
        print ("")
        redoanswer2 = input ("")
        if redoanswer2 == "A" or redoanswer2 == "a" or redoanswer2 == "A." or redoanswer2 == "a." :
            academy2 ()
        elif redoanswer2 == "B" or redoanswer2 == "b" or redoanswer2 == "B." or redoanswer2 == "b." :
            stayhome2 ()
        else:
            print ("")
            print ("OK!!! STOP BEING ANNOYING!!! JUST CHOOSE SOMETHING!!! ACTUALLY, SCRATCH THAT! LEAVE ME ALONE AND TRY AGAIN WHEN YOU CAN HANDLE THIS!!!")
    
print ("Hello user! Today we will be playing a choose your own adventure! I will give you options and simply type a, b, c, ect. Ready?")
print ("")
input ("")
print ("")
print ("Could you tell me you name please?")
print ("")
name = input ("")
print ("")
print (f"Well {name}, here we go. Let the story begin!")
print ("")
print ("You live in a small village named Falcon Feather. In this world, you can use all kinds of magic, though it is rare. Well, YOU can only use fire magic. Do you want to go to the magic academy in the capital?")
print ("")
print ("A. Yes! I will learn to use magic to the best of my ability.")
print ("B. No. I will stay home and have a relaxing year. Its too early to decide schools anyway.")
print ("")
answer1 = input ("")
if answer1 == "A" or answer1 == "a" or answer1 == "A." or answer1 == "a." :
    academy1 ()
elif answer1 == "B" or answer1 == "b" or answer1 == "B." or answer1 == "b." :
    stayhome1 ()
else:
    print ("")
    print (f"Hmmm... Looks like you didn't choose one of the options {name}. Just type a or b, not the whole sentence, okay?")
    print ("")
    redoanswer1 = input ("")
    if redoanswer1 == "A" or redoanswer1 == "a" or redoanswer1 == "A." or redoanswer1 == "a." :
        academy1 ()
    elif redoanswer1 == "B" or redoanswer1 == "b" or redoanswer1 == "B." or redoanswer1 == "b." :
        stayhome1 ()
    else:
        print ("")
        print ("OK!!! STOP BEING ANNOYING!!! JUST CHOOSE SOMETHING!!! ACTUALLY, SCRATCH THAT! LEAVE ME ALONE AND TRY AGAIN WHEN YOU CAN HANDLE THIS!!!")
